export const actionsType = {
  CURRENT_WEATHER_START: "WEATHER/CURRENT_WEATHER_START",
  CURRENT_WEATHER: "WEATHER/CURRENT_WEATHER",
  CURRENT_WEATHER_FAIL: "WEATHER/CURRENT_WEATHER_FAIL",

  TEMP_TYPE: "WEATHER/TEMP_TYPE",
  TEMP_ICON: "WEATHER/TEMP_ICON",
};
